import { Hydration } from '@components/hydration'
import Layout from '@components/layout/Layout'
import { Providers } from '@providers/index'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <Hydration>
            <Layout>{children}</Layout>
          </Hydration>
        </Providers>
      </body>
    </html>
  )
}
